// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package store

import (
	"time"
)

type Todo struct {
	ID        int32
	Content   string
	Completed bool
	CreateAt  time.Time
	IsDeleted bool
}
